-- @jniles: remove all the aggregate consumption routes
DELETE FROM role_unit WHERE `unit_id` IN (SELECT id FROM `unit` WHERE `key` IN ('TREE.AGGREGATED_STOCK_CONSUMPTION', 'REPORT.AGGREGATED_STOCK_CONSUMPTION.TITLE', 'TREE.STOCK_CONSUMPTION_GRAPH_REPORT'));
DELETE FROM `unit` WHERE `key` IN ('TREE.AGGREGATED_STOCK_CONSUMPTION', 'REPORT.AGGREGATED_STOCK_CONSUMPTION.TITLE', 'TREE.STOCK_CONSUMPTION_GRAPH_REPORT');
DELETE FROM `flux` WHERE `label` IN ('STOCK_FLUX.AGGREGATE_CONSUMPTION');

