const employeesData = [
  {
    employee_uuid : '251DB58CF3854699B66A074D1A73CE8A',
    reference : 1100,
    code : 'EMP-STAFF-01091',
    hiring_date : '2007-03-31',
    nb_enfant : 0,
    individual_salary : 0,
    account_id : 366,
    creditor_uuid : 'F867E5898D7C41CEA12B0CFD369319E1',
    function_name : null,
    display_name : 'AHMED BENALI CHÉRIF',
    sex : 'M',
    payment_uuid : null,
    payroll_configuration_id : '24',
    currency_id : '2',
    payment_date : null,
    base_taxable : 0,
    basic_salary : 0,
    gross_salary : 0,
    grade_salary : 425,
    text : 'Directeur en chef de 2ème échelon',
    net_salary : 0,
    working_day : 0,
    total_day : 0,
    daily_salary : 0,
    amount_paid : 0,
    status_id : 1,
    status : 'PAYROLL_STATUS.WAITING_FOR_CONFIGURATION',
    balance : 0,
    hrreference : 'EM.TE.1100',
    cost_center_id : 4,
    service_name : 'Maintenance and Logistics',
    negativeValue : 0,
  },
  {
    employee_uuid : '5194813A1EE446359C462D1F1BFA5A08',
    reference : 1010,
    code : 'EMP-STAFF-01001',
    hiring_date : '1992-10-31',
    nb_enfant : 0,
    individual_salary : 0,
    account_id : 366,
    creditor_uuid : 'CD6A5DCAB25D47C986560BA355D56F22',
    function_name : null,
    display_name : 'AÏCHA DIALLO KAMARA',
    sex : 'F',
    payment_uuid : null,
    payroll_configuration_id : '24',
    currency_id : '2',
    payment_date : null,
    base_taxable : 0,
    basic_salary : 0,
    gross_salary : 0,
    grade_salary : 300,
    text : 'Des hôpitaux adjoints',
    net_salary : 0,
    working_day : 0,
    total_day : 0,
    daily_salary : 0,
    amount_paid : 0,
    status_id : 1,
    status : 'PAYROLL_STATUS.WAITING_FOR_CONFIGURATION',
    balance : 0,
    hrreference : 'EM.TE.1010',
    cost_center_id : 6,
    service_name : 'Surgery',
    negativeValue : 0,
  },
  {
    employee_uuid : '07D9B06B00214CC2AC99ADDC218175B3',
    reference : 1140,
    code : 'EMP-STAFF-01131',
    hiring_date : '2022-08-31',
    nb_enfant : 0,
    individual_salary : 0,
    account_id : 366,
    creditor_uuid : '901434DA38974317828DDE1F57321C1C',
    function_name : null,
    display_name : 'ALESSANDRO BARBIERI CONTI',
    sex : 'M',
    payment_uuid : null,
    payroll_configuration_id : '24',
    currency_id : '2',
    payment_date : null,
    base_taxable : 0,
    basic_salary : 0,
    gross_salary : 0,
    grade_salary : 150,
    text : 'Agent de bureau de 1ère classe',
    net_salary : 0,
    working_day : 0,
    total_day : 0,
    daily_salary : 0,
    amount_paid : 0,
    status_id : 1,
    status : 'PAYROLL_STATUS.WAITING_FOR_CONFIGURATION',
    balance : 0,
    hrreference : 'EM.TE.1140',
    cost_center_id : 4,
    service_name : 'Maintenance and Logistics',
    negativeValue : 0,
  },
  {
    employee_uuid : '47B2B330CC27430FBE3F8B3A14BE07E2',
    reference : 1244,
    code : 'EMP-STAFF-01235',
    hiring_date : '2011-11-30',
    nb_enfant : 0,
    individual_salary : 0,
    account_id : 366,
    creditor_uuid : '4FE546A310A440599D02987DE74E29BB',
    function_name : null,
    display_name : 'ALESSANDRO PALUMBO BENEDETTI',
    sex : 'M',
    payment_uuid : null,
    payroll_configuration_id : '24',
    currency_id : '2',
    payment_date : null,
    base_taxable : 0,
    basic_salary : 0,
    gross_salary : 0,
    grade_salary : 375,
    text : 'Médecin interne',
    net_salary : 0,
    working_day : 0,
    total_day : 0,
    daily_salary : 0,
    amount_paid : 0,
    status_id : 1,
    status : 'PAYROLL_STATUS.WAITING_FOR_CONFIGURATION',
    balance : 0,
    hrreference : 'EM.TE.1244',
    cost_center_id : 6,
    service_name : 'Surgery',
    negativeValue : 0,
  },
  {
    employee_uuid : '6E1F0B85EDF04EA7B6F06B0E5E17D6E6',
    reference : 1076,
    code : 'EMP-STAFF-01067',
    hiring_date : '2020-05-31',
    nb_enfant : 0,
    individual_salary : 0,
    account_id : 366,
    creditor_uuid : '1DAD3424596F436EABEB235ADD344A1B',
    function_name : null,
    display_name : 'ALESSIA MORETTI LOMBARDI',
    sex : 'F',
    payment_uuid : null,
    payroll_configuration_id : '24',
    currency_id : '2',
    payment_date : null,
    base_taxable : 0,
    basic_salary : 0,
    gross_salary : 0,
    grade_salary : 375,
    text : 'Médecin interne',
    net_salary : 0,
    working_day : 0,
    total_day : 0,
    daily_salary : 0,
    amount_paid : 0,
    status_id : 1,
    status : 'PAYROLL_STATUS.WAITING_FOR_CONFIGURATION',
    balance : 0,
    hrreference : 'EM.TE.1076',
    cost_center_id : 2,
    service_name : 'Billing and Accounting Department',
    negativeValue : 0,
  },
  {
    employee_uuid : '50894EDF9DFE4A049986611656B2EA0A',
    reference : 1176,
    code : 'EMP-STAFF-01167',
    hiring_date : '2011-07-31',
    nb_enfant : 0,
    individual_salary : 0,
    account_id : 366,
    creditor_uuid : '6C715EC1A4B942199E8C321E0BA760AB',
    function_name : null,
    display_name : 'ALEXEI FEDOROV SOKOLOV',
    sex : 'M',
    payment_uuid : null,
    payroll_configuration_id : '24',
    currency_id : '2',
    payment_date : null,
    base_taxable : 0,
    basic_salary : 0,
    gross_salary : 0,
    grade_salary : 300,
    text : 'Des hôpitaux adjoints',
    net_salary : 0,
    working_day : 0,
    total_day : 0,
    daily_salary : 0,
    amount_paid : 0,
    status_id : 1,
    status : 'PAYROLL_STATUS.WAITING_FOR_CONFIGURATION',
    balance : 0,
    hrreference : 'EM.TE.1176',
    cost_center_id : 3,
    service_name : 'Internal Medicine',
    negativeValue : 0,
  },
  {
    employee_uuid : 'D0CDDEF17234498C9A8EE283800CCDC1',
    reference : 1090,
    code : 'EMP-STAFF-01081',
    hiring_date : '2003-10-31',
    nb_enfant : 0,
    individual_salary : 0,
    account_id : 366,
    creditor_uuid : '2604EC98CE6F48979114DCD96B60A97E',
    function_name : null,
    display_name : 'ALI DIARRA KEITA',
    sex : 'M',
    payment_uuid : null,
    payroll_configuration_id : '24',
    currency_id : '2',
    payment_date : null,
    base_taxable : 0,
    basic_salary : 0,
    gross_salary : 0,
    grade_salary : 375,
    text : 'Médecin interne',
    net_salary : 0,
    working_day : 0,
    total_day : 0,
    daily_salary : 0,
    amount_paid : 0,
    status_id : 1,
    status : 'PAYROLL_STATUS.WAITING_FOR_CONFIGURATION',
    balance : 0,
    hrreference : 'EM.TE.1090',
    cost_center_id : 3,
    service_name : 'Internal Medicine',
    negativeValue : 0,
  },
  {
    employee_uuid : '2D67ED83117A49DDBA935845E11CE368',
    reference : 1038,
    code : 'EMP-STAFF-01029',
    hiring_date : '1997-06-30',
    nb_enfant : 0,
    individual_salary : 0,
    account_id : 366,
    creditor_uuid : '8706B3D58BA84AB2BD582CC063522701',
    function_name : null,
    display_name : 'ALICE MARTIN ROUSSEAU',
    sex : 'F',
    payment_uuid : null,
    payroll_configuration_id : '24',
    currency_id : '2',
    payment_date : null,
    base_taxable : 0,
    basic_salary : 0,
    gross_salary : 0,
    grade_salary : 375,
    text : 'Médecin interne',
    net_salary : 0,
    working_day : 0,
    total_day : 0,
    daily_salary : 0,
    amount_paid : 0,
    status_id : 1,
    status : 'PAYROLL_STATUS.WAITING_FOR_CONFIGURATION',
    balance : 0,
    hrreference : 'EM.TE.1038',
    cost_center_id : 6,
    service_name : 'Surgery',
    negativeValue : 0,
  },
  {
    employee_uuid : '1CFDCE4844C54752849BBB3C4D5F72FC',
    reference : 1211,
    code : 'EMP-STAFF-01202',
    hiring_date : '2021-02-28',
    nb_enfant : 0,
    individual_salary : 0,
    account_id : 366,
    creditor_uuid : '701208ABEE6B4D70BFA87AEC211C3F31',
    function_name : null,
    display_name : 'ALPHA CAMARA SOUMAH',
    sex : 'M',
    payment_uuid : null,
    payroll_configuration_id : '24',
    currency_id : '2',
    payment_date : null,
    base_taxable : 0,
    basic_salary : 0,
    gross_salary : 0,
    grade_salary : 150,
    text : 'Agent de bureau de 1ère classe',
    net_salary : 0,
    working_day : 0,
    total_day : 0,
    daily_salary : 0,
    amount_paid : 0,
    status_id : 1,
    status : 'PAYROLL_STATUS.WAITING_FOR_CONFIGURATION',
    balance : 0,
    hrreference : 'EM.TE.1211',
    cost_center_id : 2,
    service_name : 'Billing and Accounting Department',
    negativeValue : 0,
  },
  {
    employee_uuid : '0D68B9D64D1F45EDA43302D619F7CE98',
    reference : 1268,
    code : 'EMP-STAFF-0202504',
    hiring_date : '1982-12-31',
    nb_enfant : 0,
    individual_salary : 0,
    account_id : 366,
    creditor_uuid : '10F10BC632F9439C8C6EF5591E91324D',
    function_name : null,
    display_name : 'AMELIA ROSE THORNTON',
    sex : 'F',
    payment_uuid : null,
    payroll_configuration_id : '24',
    currency_id : '2',
    payment_date : null,
    base_taxable : 0,
    basic_salary : 0,
    gross_salary : 0,
    grade_salary : 225,
    text : 'Attaché de bureau de 2ème classe',
    net_salary : 0,
    working_day : 0,
    total_day : 0,
    daily_salary : 0,
    amount_paid : 0,
    status_id : 1,
    status : 'PAYROLL_STATUS.WAITING_FOR_CONFIGURATION',
    balance : 0,
    hrreference : 'EM.TE.1268',
    cost_center_id : 4,
    service_name : 'Maintenance and Logistics',
    negativeValue : 0,
  },
  {
    employee_uuid : '61A94E652FB44ACA9E5DBC3819A96AF2',
    reference : 1238,
    code : 'EMP-STAFF-01229',
    hiring_date : '2017-07-31',
    nb_enfant : 0,
    individual_salary : 0,
    account_id : 366,
    creditor_uuid : 'BDE83F9DF7BB4922AF74169D454D53C6',
    function_name : null,
    display_name : 'ANDREW BELL COOPER',
    sex : 'M',
    payment_uuid : null,
    payroll_configuration_id : '24',
    currency_id : '2',
    payment_date : null,
    base_taxable : 0,
    basic_salary : 0,
    gross_salary : 0,
    grade_salary : 375,
    text : 'Médecin interne',
    net_salary : 0,
    working_day : 0,
    total_day : 0,
    daily_salary : 0,
    amount_paid : 0,
    status_id : 1,
    status : 'PAYROLL_STATUS.WAITING_FOR_CONFIGURATION',
    balance : 0,
    hrreference : 'EM.TE.1238',
    cost_center_id : 4,
    service_name : 'Maintenance and Logistics',
    negativeValue : 0,
  },
  {
    employee_uuid : '02E4FE5BC16C4AA2BF379A7FC097855C',
    reference : 1258,
    code : 'EMP-STAFF-01249',
    hiring_date : '2011-11-30',
    nb_enfant : 0,
    individual_salary : 0,
    account_id : 366,
    creditor_uuid : '9D8245FA9F034DCA8B7922E180C8B315',
    function_name : null,
    display_name : 'ANTOINE DUFRESNE PERRIN',
    sex : 'M',
    payment_uuid : null,
    payroll_configuration_id : '24',
    currency_id : '2',
    payment_date : null,
    base_taxable : 0,
    basic_salary : 0,
    gross_salary : 0,
    grade_salary : 400,
    text : 'Directeur en chef de 1ère échelon',
    net_salary : 0,
    working_day : 0,
    total_day : 0,
    daily_salary : 0,
    amount_paid : 0,
    status_id : 1,
    status : 'PAYROLL_STATUS.WAITING_FOR_CONFIGURATION',
    balance : 0,
    hrreference : 'EM.TE.1258',
    cost_center_id : 4,
    service_name : 'Maintenance and Logistics',
    negativeValue : 0,
  },
  {
    employee_uuid : '36FBAB263F88442E9D02079B09FCD957',
    reference : 1161,
    code : 'EMP-STAFF-01152',
    hiring_date : '1996-02-29',
    nb_enfant : 0,
    individual_salary : 0,
    account_id : 366,
    creditor_uuid : '6C6193CA2A564407ADC42E785DCBC552',
    function_name : null,
    display_name : 'ANTOINE LEMOINE DUFRESNE',
    sex : 'M',
    payment_uuid : null,
    payroll_configuration_id : '24',
    currency_id : '2',
    payment_date : null,
    base_taxable : 0,
    basic_salary : 0,
    gross_salary : 0,
    grade_salary : 300,
    text : 'Des hôpitaux adjoints',
    net_salary : 0,
    working_day : 0,
    total_day : 0,
    daily_salary : 0,
    amount_paid : 0,
    status_id : 1,
    status : 'PAYROLL_STATUS.WAITING_FOR_CONFIGURATION',
    balance : 0,
    hrreference : 'EM.TE.1161',
    cost_center_id : 6,
    service_name : 'Surgery',
    negativeValue : 0,
  },
  {
    employee_uuid : '439A7E097A8E4B5AAB7E165C870FDA8E',
    reference : 1034,
    code : 'EMP-STAFF-01025',
    hiring_date : '1991-10-31',
    nb_enfant : 0,
    individual_salary : 0,
    account_id : 366,
    creditor_uuid : 'DA3EA4642F0C47BE99413C80433E78E7',
    function_name : null,
    display_name : 'ANTONELLA NAVARRO VILLALOBOS',
    sex : 'F',
    payment_uuid : null,
    payroll_configuration_id : '24',
    currency_id : '2',
    payment_date : null,
    base_taxable : 0,
    basic_salary : 0,
    gross_salary : 0,
    grade_salary : 325,
    text : 'Médecin chef clinique',
    net_salary : 0,
    working_day : 0,
    total_day : 0,
    daily_salary : 0,
    amount_paid : 0,
    status_id : 1,
    status : 'PAYROLL_STATUS.WAITING_FOR_CONFIGURATION',
    balance : 0,
    hrreference : 'EM.TE.1034',
    cost_center_id : 3,
    service_name : 'Internal Medicine',
    negativeValue : 0,
  },
  {
    employee_uuid : '1D7B1BC4E5264C8D8A87145962147131',
    reference : 1203,
    code : 'EMP-STAFF-01194',
    hiring_date : '2012-07-31',
    nb_enfant : 0,
    individual_salary : 0,
    account_id : 366,
    creditor_uuid : '8AB76E1687824337BABDB48DB87C7954',
    function_name : null,
    display_name : 'ANTONIO CRUZ MENDEZ',
    sex : 'M',
    payment_uuid : null,
    payroll_configuration_id : '24',
    currency_id : '2',
    payment_date : null,
    base_taxable : 0,
    basic_salary : 0,
    gross_salary : 0,
    grade_salary : 325,
    text : 'Médecin chef clinique',
    net_salary : 0,
    working_day : 0,
    total_day : 0,
    daily_salary : 0,
    amount_paid : 0,
    status_id : 1,
    status : 'PAYROLL_STATUS.WAITING_FOR_CONFIGURATION',
    balance : 0,
    hrreference : 'EM.TE.1203',
    cost_center_id : 2,
    service_name : 'Billing and Accounting Department',
    negativeValue : 0,
  },
  {
    employee_uuid : '4D51E9F3FEB24F1693DA4F0F90DED8C7',
    reference : 1141,
    code : 'EMP-STAFF-01132',
    hiring_date : '2009-10-31',
    nb_enfant : 0,
    individual_salary : 0,
    account_id : 366,
    creditor_uuid : 'DA14C0A873A04E6C8EEAF749A099E363',
    function_name : null,
    display_name : 'ANTONIO DE SANTIS FERRARI',
    sex : 'M',
    payment_uuid : null,
    payroll_configuration_id : '24',
    currency_id : '2',
    payment_date : null,
    base_taxable : 0,
    basic_salary : 0,
    gross_salary : 0,
    grade_salary : 400,
    text : 'Directeur en chef de 1ère échelon',
    net_salary : 0,
    working_day : 0,
    total_day : 0,
    daily_salary : 0,
    amount_paid : 0,
    status_id : 1,
    status : 'PAYROLL_STATUS.WAITING_FOR_CONFIGURATION',
    balance : 0,
    hrreference : 'EM.TE.1141',
    cost_center_id : 6,
    service_name : 'Surgery',
    negativeValue : 0,
  },
  {
    employee_uuid : '8A3D87A70A174DB3976AAD5256F32AB3',
    reference : 1240,
    code : 'EMP-STAFF-01231',
    hiring_date : '1991-09-30',
    nb_enfant : 0,
    individual_salary : 0,
    account_id : 366,
    creditor_uuid : '0608BBE55F3D4D9F825468F4142928B6',
    function_name : null,
    display_name : 'ANTONIO RICCI MORETTI',
    sex : 'M',
    payment_uuid : null,
    payroll_configuration_id : '24',
    currency_id : '2',
    payment_date : null,
    base_taxable : 0,
    basic_salary : 0,
    gross_salary : 0,
    grade_salary : 250,
    text : 'Des hôpitaux 1ère échelon',
    net_salary : 0,
    working_day : 0,
    total_day : 0,
    daily_salary : 0,
    amount_paid : 0,
    status_id : 1,
    status : 'PAYROLL_STATUS.WAITING_FOR_CONFIGURATION',
    balance : 0,
    hrreference : 'EM.TE.1240',
    cost_center_id : 3,
    service_name : 'Internal Medicine',
    negativeValue : 0,
  }];

module.exports = employeesData;
