name: Super Linter

on:
  pull_request:
  push:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest

    # note this only works from the BHIMA repo,
    # not from froks because the permissions are 
    # hard-coded to read-only on forked repos.
    permissions:
      contents: read
      packages: read
      issues: write
      pull-requests: write
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Run the linters
        uses: super-linter/super-linter/slim@4ce20838b8ab83717e78138c5b3a1407148e0918 # v8.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          SAVE_SUPER_LINTER_SUMMARY: true
          ENABLE_GITHUB_ACTIONS_STEP_SUMMARY: true

          VALIDATE_ALL_CODEBASE: true
          VALIDATE_BASH: false
          VALIDATE_BIOME_FORMAT: false
          VALIDATE_BIOME_LINT: false
          VALIDATE_GIT_COMMITLINT: false
          VALIDATE_GITLEAKS: false
          VALIDATE_JSON: false
          VALIDATE_JSCPD: false
          VALIDATE_MARKDOWN: false
          VALIDATE_PYTHON: false 
          VALIDATE_PYTHON_RUFF: false
          VALIDATE_SPELL_CODESPELL: false
          VALIDATE_SQLFLUFF: false
          VALIDATE_YAML: false
