name: Super Linter

on:
  pull_request:
  push:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  issues: write
  packages: read
  pull-requests: write
  statuses: write

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Run the linters
        uses: super-linter/super-linter/slim@v8.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          ENABLE_GITHUB_PULL_REQUEST_SUMMARY_COMMENT: true
          ENABLE_GITHUB_ACTIONS_STEP_SUMMARY: true
          SAVE_SUPER_LINTER_SUMMARY: true
          VALIDATE_ALL_CODEBASE: true

          VALIDATE_BASH: false
          VALIDATE_BIOME_FORMAT: false
          VALIDATE_BIOME_LINT: false
          VALIDATE_GIT_COMMITLINT: false
          VALIDATE_GITLEAKS: false
          VALIDATE_JSCPD: false
          VALIDATE_JSON: false
          VALIDATE_MARKDOWN: false
          VALIDATE_SPELL_CODESPELL: false
          VALIDATE_SQLFLUFF: false
          VALIDATE_TRIVY: false
          VALIDATE_YAML: false
